-- public.perfil definition

-- Drop table

-- DROP TABLE perfil;

CREATE TABLE perfil (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ativo bool NULL,
	data_alteracao timestamp NULL,
	data_inclusao timestamp NULL,
	id_usuario_alteracao int4 NULL,
	id_usuario_inclusao int4 NULL,
	nome varchar(255) NULL,
	CONSTRAINT perfil_pkey PRIMARY KEY (id)
);


-- public.usuario definition

-- Drop table

-- DROP TABLE usuario;

CREATE TABLE usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	senha varchar(255) NULL,
	ativo boolean default true,
	primeiro_acesso boolean default false, 
	aceite_termos_uso boolean default false,
	data_ultimo_login timestamp without time zone,
	id_usuario_inclusao integer,
    data_inclusao timestamp without time zone,
    id_usuario_alteracao integer,
    data_alteracao timestamp without time zone,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);


-- public.cliente_email definition

-- Drop table

-- DROP TABLE cliente_email;

CREATE TABLE cliente_email (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cnpj varchar(16) NULL,
	email varchar(255) NULL,
	razao_social varchar(255) NULL,
	id_usuario int8 NULL,
	id_usuario_inclusao integer,
    data_inclusao timestamp without time zone,
    id_usuario_alteracao integer,
    data_alteracao timestamp without time zone,
	CONSTRAINT cliente_email_pkey PRIMARY KEY (id),
	CONSTRAINT fk8oo4vafee2ub4296uufbepj1y FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);


-- public.usuario_perfis definition

-- Drop table

-- DROP TABLE usuario_perfis;

CREATE TABLE usuario_perfis (
	usuario_id int8 NOT NULL,
	perfis_id int8 NOT NULL,
	CONSTRAINT fk7bhs80brgvo80vhme3u8m6ive FOREIGN KEY (perfis_id) REFERENCES perfil(id),
	CONSTRAINT fks91tgiyagbilt959wbufiphgc FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);